@HostAddress = http://localhost:5000
@Token = Bearer 

GET {{HostAddress}}/api/Projects
Authorization: {{Token}}
Accept: application/json

###

GET {{HostAddress}}/api/Projects?search=Desenvolvimento
Authorization: {{Token}}
Accept: application/json

###

POST {{HostAddress}}/api/Projects
Authorization: {{Token}}
Content-Type: application/json
Accept: application/json

{
  "title": "Pojeto de Desenvolvimento",
  "description": "Desenvolvimento de um sistema web",
  "idClient": 1,
  "idFreelancer": 2,
  "totalCost": 5000.0
}

###

GET {{HostAddress}}/api/Projects/1
Authorization: {{Token}}
Accept: application/json

###

PUT {{HostAddress}}/api/Projects
Authorization: {{Token}}
Content-Type: application/json
Accept: application/json

{
  "idProject": 1,
  "title": "Projeto de Desenvolvimento",
  "description": "Desenvolvimento de um sistema web",
  "totalCost": 6000.0
}

###

DELETE {{HostAddress}}/api/Projects/1
Authorization: {{Token}}
Accept: application/json

###

PUT {{HostAddress}}/api/Projects/1/start
Authorization: {{Token}}
Accept: application/json

###

PUT {{HostAddress}}/api/Projects/1/complete
Authorization: {{Token}}
Accept: application/json

###

POST {{HostAddress}}/api/Projects/comments
Authorization: {{Token}}
Content-Type: application/json
Accept: application/json

{
  "content": "Muito top o progresso!",
  "idUser": 2,
  "idProject": 1
}

###

GET {{HostAddress}}/api/Skills
Authorization: {{Token}}
Accept: application/json

###

POST {{HostAddress}}/api/Skills
Authorization: {{Token}}
Content-Type: application/json
Accept: application/json

{
  "description": "C#"
}

###

GET {{HostAddress}}/api/Users/1
Authorization: {{Token}}
Accept: application/json

###

POST {{HostAddress}}/api/Users
Content-Type: application/json
Accept: application/json

{
  "fullName": "Abner Oliveira",
  "email": "abner@email.com",
  "birthDate": "1997-02-16T00:00:00",
  "password": "123456",
  "role": "freelancer"
}

###

POST {{HostAddress}}/api/Users
Content-Type: application/json
Accept: application/json

{
  "fullName": "João Silva Oliveira",
  "email": "joao_ol@email.com",
  "birthDate": "1990-05-01T00:00:00",
  "password": "123456",
  "role": "client"
}

###

POST {{HostAddress}}/api/Users
Content-Type: application/json
Accept: application/json

{
  "fullName": "Stéffany Oliveira",
  "email": "ste@email.com",
  "birthDate": "1999-02-24T00:00:00",
  "password": "123456",
  "role": "client"
}

###

PUT {{HostAddress}}/api/Users/1/skills
Authorization: {{Token}}
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "skillIds": [
    1
  ]
}

###

PUT {{HostAddress}}/api/Users/1/profile-picture
Authorization: {{Token}}
Content-Type: multipart/form-data
Accept: application/json

(file deve ser enviado como binary)

###

PUT {{HostAddress}}/api/Users/login
Content-Type: application/json
Accept: application/json

{
  "email": "joao_ol@email.com",
  "password": "123456"
}

###

PUT {{HostAddress}}/api/Users/login
Content-Type: application/json
Accept: application/json

{
  "email": "abner@email.com",
  "password": "123456"
}

###

PUT {{HostAddress}}/api/Users/login
Content-Type: application/json
Accept: application/json

{
  "email": "ste@email.com",
  "password": "123456"
}

### Request Password Recovery
POST {{HostAddress}}/users/password-recovery/request
Content-Type: application/json

{
  "email": "vabes77746@lhory.com"
}

### Validate Recovery Code
POST {{HostAddress}}/users/password-recovery/validate
Content-Type: application/json

{
  "email": "xihisa5599@fenxz.com",
  "code": "467001"
}

### Change Password
POST {{HostAddress}}/users/password-recovery/change
Content-Type: application/json

{
  "email": "xihisa5599@fenxz.com",
  "code": "467001",
  "newPassword": "newStrongPassword123"
}